name: TF Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    env:
      TF_VAR_project_name: nginx-app

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install tf
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: AWS creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: tf init
        run: terraform init

      - name: tf fmt
        run: terraform fmt

      - name: tf validate
        run: terraform validate

      - name: tf plan
        run: terraform plan

      # here is apply only when it pushed to the main
      - name: tf apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve